<?php foreach ($this->files as $file) { ?>
                <tr class="<?php echo $file['utilise'] ? '' : 'filenotused'; ?>" id="fileid_<?php echo $file['id']; ?>">
                    <td>
                        <a  class="previsu" href="<?php echo $file['path']; ?>" title="<?php echo $file['rewriting']; ?>">
                            <img src="<?php echo $file['path_mini']; ?>" alt="<?php echo $file['rewriting']; ?>" />
                        </a>
                    </td>
                    <td><?php echo $file['poids']; ?></td>
                    <td><?php if (isset($file['width'])) echo $file['width']; ?></td>
                    <td><?php if (isset($file['height'])) echo $file['height']; ?></td>
                    <td><?php echo Slrfw\Tools::formate_date_nombre(substr($file['date_crea'], 0, 10), '-', '/'); ?><br /><?php echo substr($file['date_crea'], 11); ?></td>
                    <td><?php echo $file['utilise'] ? 'Oui' : 'Non'; ?></td>
                    <td>
                        <div class="btn-a gradient-blue"><a href="<?php echo $file['path']; ?>" class="previsu"><img alt="Prévisualisation" src="app/back/img/voir.png" /></a></div>
                        <div class="btn-a gradient-blue"><a href="" class="delete-file"><img alt="Supprimer" src="app/back/img/white/trash_stroke_16x16.png" /></a></div>
                    </td>
                </tr>
<?php } ?>


