<style>
    #tableau_wrapper select {
        margin-bottom: 0;
        width: auto;
    }

    #tableau td {
            overflow: hidden; /* this is what fixes the expansion */
            white-space: normal;
            word-wrap: break-word;
            max-width: 400px;


        }

        #tableau_length select {
            width: auto;
            margin-bottom: 0px;
        }


        #tableau_wrapper input {
            height: auto;
            margin-bottom: 0px;
        }

        #tableau_wrapper .fg-toolbar.ui-corner-tl {
            border-radius: 6px 6px 0px 0px;
        }

        #tableau_wrapper .fg-toolbar.ui-corner-bl {
            border-radius: 0px 0px 6px 6px;
        }


        #tableau_wrapper .ui-widget-header {
            margin: 0;
            box-shadow: none;
            border: none;
            border-radius: 0px;


        }

        thead input { width: 100% }
        #tableau tfoot input.search_init, #tableau tfoot input.text_filter { font-size : 11px; }

        select.select_filter {max-width: 100px;font-size : 11px;}



        #tableau table { width: 100%;}

        #tableau table a { text-decoration: underline; }
        #tableau table tr  >  td { border: 0px;text-align: left;vertical-align: top;  }
        #tableau table tr  >  td:first-child {  padding-left: 50px;width: 100px;font-weight: bold;  }
        #tableau table  >  tbody {
            border-top: 0px dotted #333333;
        }
        #tableau table  >  tbody tr:hover {
            background-color: #4A9DD7;
            color: #FFF;
        }
        #tableau tbody tr.even, #tableau tbody tr.odd,
        #tableau tbody tr.even td a, #tableau tbody tr.odd td a{
            color: #000;

        }
        #tableau tbody tr.even:hover, #tableau > tbody tr.even td.highlighted {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tbody tr.even:hover > td >  a, #tableau > tbody tr.even td.highlighted > a {
            color: #FFF;
        }


        #tableau tbody tr.odd:hover, #tableau > tbody tr.odd td.highlighted {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tbody tr.odd:hover > td > a, #tableau > tbody tr.odd td.highlighted > a {
            color: #FFF;
        }


        #tableau tr.even:hover {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tr.even:hover > td.sorting_1 {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tr.even:hover > td.sorting_2 {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tr.even:hover > td.sorting_3 {
            background-color: #E2FF89;
            color: #FFF;
        }

        #tableau tr.odd:hover {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tr.odd:hover > td.sorting_1 {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tr.odd:hover > td.sorting_2 {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tr.odd:hover > td.sorting_3 {
            background-color: #117ECA;
            color: #FFF;
        }


</style>
        <div>
            <a href="#" class="btn btn-small btn-success" id="pickfiles"><i class="icon-folder-open"></i> Ajouter un fichier</a>
        </div>

        <table id="tableau" class="display" style="width:100%;">
            <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th>Taille</th>
                    <th>Date / Heure</th>
                    <th style="width: 50px;">&nbsp;</th>
                </tr>
            </thead>

            <tbody id="foldercontent">

<?php foreach ($this->files as $file) { ?>

                <tr id="fileid_<?php echo $file['id']; ?>">
                    <td>
                        <a target="_blank" class="previsu" href="<?php echo $file['path']; ?>" title="<?php echo $file['rewriting']; ?>">
                            <img class="<?php echo $file['class']; ?>" src="<?php echo $file['path_mini']; ?>" alt="<?php echo $file['rewriting']; ?>" />
                        </a>
                    </td>
                    <td><?php echo $file['poids']; ?></td>
                    <td><?php echo \Slrfw\Tools::formate_date_nombre(substr($file['date_crea'], 0, 10), '-', '/'); ?><br /><?php echo substr($file['date_crea'], 11); ?></td>
                    <td class="center">
                        <div class="btn-toolbar">
                            <div class="btn-group">
                                <a href="<?php echo $file['path']; ?>" class="btn btn-info previsu" title="Visualiser"><i class="icon-camera"></i></a>
                            </div>
                        </div>
                    </td>
                </tr>

<?php } ?>

            </tbody>
        </table>
