                        <h1>Gestion des pages</h1>

<?php
    $this->add('breadcrumbs.phtml');
?>

                        <h2><?php echo ($this->pages[BACK_ID_VERSION]->getMeta() ? 'Modification de ' : 'Création de ') . strtolower($this->pages[BACK_ID_VERSION]->getGabarit()->getLabel()); ?></h2>

<?php
    if (count($this->versions) > 0) {
?>
                        <div>
<?php
        foreach ($this->versions as $id_version => $version) {
            $page = $this->pages[$id_version];
?>
                            <div style="height: 54px;float: left;">
                                <div class="btn-a gradient-blue" style="margin-bottom: 5px;display:block;">
                                    <a title="<?php echo $version['nom']; ?>" class="openlang <?php echo $id_version == BACK_ID_VERSION ? 'active' : 'translucide'; ?>">
                                        Langue : <img src="app/back/img/flags/png/<?php echo strtolower($version['suf']); ?>.png" alt="<?php echo $version['nom']; ?>" />
                                    </a>
                                </div>

<?php
            if ($page->getMeta("rewriting") != "") {
                if ($page->getGabarit()->getMake_hidden()
                    || $this->utilisateur->get("niveau") == "solire"
                    || !$page->getMeta("visible")
                ) {
?>
                                <div style="margin-left: 6px;margin-top: -7px;">
                                    <label style="color:#A1A1A1;display:inline;text-shadow:none;margin-left:10px;" for="visible-<?php echo $id_version; ?>">Visible : </label>
                                    <input class="visible-lang visible-lang-<?php echo $page->getMeta("id") . '-' . $id_version; ?>" style="margin:0;" value="<?php echo $page->getMeta("id") . '|' . $id_version; ?>" id="visible-<?php echo $id_version; ?>" type="checkbox"<?php if ($page->getMeta("visible")) { echo ' checked="checked"'; }?> />
                                </div>
<?php
                }
            }else {
                if (count($this->versions) > 1) {
?>
                                <span class="notification gradient-red" style="margin-left: 6px;">Non traduit</span>
<?php
                }
            }
?>
                            </div>
<?php
        }
?>
                        </div>

<?php
    }

    foreach ($this->pages as $page) {
?>
                        <div class="langue" id="langue_<?php echo $page->getMeta('id_version'); ?>" style="clear:both;<?php if ($page->getMeta('id_version') != BACK_ID_VERSION && count($this->pages) > 1) { echo ' display:none;'; } ?>">
<?php
        if (count($this->versions) > 1) {
?>
                        <div style="margin-top:0" class="clearin"></div>

                        <div>
                            <select class="compareversion-other fl" style="display:block;">
<?php
            foreach ($this->versions as $id_version => $version) {
                if ($id_version != $page->getMeta('id_version')) {
?>
                                <option value="<?php echo $id_version . '|' . strtolower($version['suf']); ?>"><?php echo $version['nom']; ?></option>
<?php
                }
            }
?>
                            </select>

                            <button class="btn-a gradient-green fl compareversion-submit" style="padding: 9px 18px; font-size: 12px; display: block; font-family: Arial; line-height: 12px;">Comparer</button>
                            <button class="btn-a gradient-green fl compareversion-hide" style="padding: 9px 18px; font-size: 12px; display: block; font-family: Arial; line-height: 12px;">Cacher</button>
                        </div>
<?php
        }
?>

                        <div style="margin-top:0" class="clearin"></div>
<?php
        if (isset($this->redirections[$page->getMeta('id_version')])) {
            $redirections = $this->redirections[$page->getMeta('id_version')];
        } else {
            $redirections = array();
        }
        echo $page->getForm('back/page/save.html', 'back/page/liste.html', $redirections, $this->authors[$page->getMeta('id_version')]);
?>
                        </div>

<?php
    }
?>

<?php
    if (isset($_GET['popup']) && $_GET['popup'] == 'more') {
?>

                        <div class="modal  hide fade" id="modalMore" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                <h3 id="myModalLabel">Que voulez-vous faire ?</h3>
                            </div>

                            <div class="modal-body">
                                <dl class="">

<?php
        $page = $this->pages[BACK_ID_VERSION];

        if ($page->getMeta("rewriting") != '') {
            if ($page->getGabarit()->getMake_hidden()
                || $this->utilisateur->get('niveau') == 'solire'
                || !$page->getMeta('visible')
            ) {
?>
                                    <dt>Gérer la visibité :</dt><br /><dd><img src="app/back/img/flags/png/<?php echo strtolower($this->versions[BACK_ID_VERSION]['suf']); ?>.png" alt="" />
                                    <input class="visible-lang visible-lang-<?php echo $page->getMeta("id") . '-' . BACK_ID_VERSION; ?>" style="margin:0;" value="<?php echo $page->getMeta('id') . '|' . BACK_ID_VERSION; ?>" id="visible-<?php echo BACK_ID_VERSION; ?>" style="margin:0;" <?php echo ($page->getMeta('visible') ? 'checked="checked"' : ''); ?> type="checkbox" /><dd>
<?php
            }
        }
?>
                                    <br />
                                    <br />
                                    <dt>Editer une autre page :</dt>
                                    <br />
                                    <dd>
                                        <div>
                                            <input type="text" placeholder="Recherche" class="search live-search ui-autocomplete-input" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true">
                                        </div>
                                    </dd>
                                    <br />

                                    <dt>Créer un nouveau contenu :</dt>
                                    <br />
                                    <dd>
                                        <div style="min-height: 50px;">
                                            <?php $this->add("template/button.phtml"); ?>
                                        </div>
                                    </dd>
                                </dl>
                            </div>

                            <div class="modal-footer">
                                <button class="btn-a gradient-grey btn-large" onclick="var link = $('.back-to-list a').attr('href');window.location = link;">Quitter</button>
                                <button class="btn-a gradient-grey btn-large" data-dismiss="modal" onclick="$('.formprev').click()" aria-hidden="true"><b>Prévisualiser</b></button>
                                <button class="btn-a gradient-blue btn-large" data-dismiss="modal" aria-hidden="true">Continuer l'édition de cette page</button>
                            </div>
                        </div>
<?php
    }
?>
<?php $this->add("template/cropdialog.phtml"); ?>