<table class="w640" border="0" cellpadding="0" cellspacing="0" width="640">
    <tbody>
        <tr>
            <td class="w30" width="30"></td>
            <td class="w580" width="580">
                <repeater>
                    <layout label="Text only">
                        <table class="w580" border="0" cellpadding="0" cellspacing="0" width="580">
                            <tbody>
                            <tr>
                                <td colspan="2" class="w580" width="580">
                                    <p class="article-title-2" align="left">Obtenez votre nouveau mot de passe en cliquant sur le lien : </p>
                                    <div class="article-content" align="left">
                                        <a href="<?php echo Slrfw\Registry::get('basehref') . $this->url; ?>">Voir mon nouveau mot de passe</a>
                                    </div>
                                </td>
                            </tr>

                            <tr><td class="w580" height="10" width="580"></td></tr>
                        </tbody></table>
                    </layout>
                </repeater>
            </td>
            <td class="w30" width="30"></td>
        </tr>
    </tbody>
</table>