                                    <p class="article-title-2" align="left">Obtenez votre nouveau mot de passe en cliquant sur le lien : </p>
                                    <div class="article-content" align="left">
                                        <a href="<?php echo Slrfw\Registry::get('basehref') . $this->url; ?>">Voir mon nouveau mot de passe</a>
                                    </div>
